#24 added the check for the mysql.sock symlink

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -8,14 +8,6 @@ function check_installation {
   hash $1 2>/dev/null || { echo >&2 "ERROR: $1 is not available."; abort; }
 }
 
-function check_mysql {
-  check_installation mysql
-  mysql --version | grep "Distrib 5" >/dev/null || {
-    echo >&2 "you need mysql version >= 5."; abort;
-  }
-  echo "✓ mysql is ok."
-}
-
 function check_ruby {
   check_installation ruby
   ruby -v | grep "ruby 2" >/dev/null || {
@@ -30,6 +22,25 @@ function check_node {
     echo >&2 "you need node version >= 0.10."; abort;
   }
   echo "✓ node is ok."
+}
+
+function check_mysql {
+  check_installation mysql
+  mysql --version | grep "Distrib 5" >/dev/null || {
+    echo >&2 "you need mysql version >= 5."; abort;
+  }
+  echo "✓ mysql is ok."
+}
+
+function check_mysqld {
+  if [ ! -h /var/mysql/mysql.sock ]; then
+    ln -s /var/mysql/mysql.sock /tmp/mysql.sock  && chmod 755 /tmp/mysql.sock
+  fi
+
+  mysqladmin ping | grep "mysqld is alive" >/dev/null || {
+    echo >&2 "mysqld is not currently running."; abort;
+  }
+  echo "✓ mysqld is running"
 }
 
 function restore_database {
@@ -61,9 +72,10 @@ function install_node_packages {
 }
 
 echo "setting up movimento-sem-terra/site-novo..."
-check_mysql
 check_ruby
 check_node
+check_mysql
+check_mysqld
 restore_database $1
 install_gems
 install_node_packages
